#!/bin/sh
#
# Copyright (c) 2019-2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE DISCLAIMED.  IN NO
# EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DESCRIPTION:  DIAG MSM + DIAG_MDM + QDSS MSM + QDSS_MDM + DUN + DPL + RMNET + ADB

echo "Switching to composition number 0x90E5"

if [ "$1" = "y" ]; then
	num="1"
	mode="hsic"
else
	num="0"
	mode="hsusb"
fi

if [ "$#" -ge 2 ]; then
	delay=$2
else
	delay="0"
fi

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

run_configfs() {
	echo start > /data/usb_bind_in_progress
	if [ $from_adb = "n" ]
	then
		pkill adbd
		sleep 1
	fi
	cd /sys/kernel/config/usb_gadget/g1
	rm os_desc/c* 2> /dev/null
	rm configs/c*/f* 2> /dev/null
	rm -rf configs/c.2 configs/c.3 2> /dev/null
	echo 0x05c6 > idVendor
	echo 0x90E5 > idProduct
	if [ -e functions/diag.diag/pid ]; then
		echo 0x90E5 > functions/diag.diag/pid
	fi
	echo "diag_diag_mdm_qdss_qdss_mdm_dun_dpl_rmnet_adb" > configs/c.1/strings/0x409/configuration
	if [ -e functions/ffs.diag ]; then
		ln -s functions/ffs.diag configs/c.1/f1
	else
		ln -s functions/diag.diag configs/c.1/f1
	fi
	ln -s functions/diag.diag_mdm configs/c.1/f2
	ln -s functions/qdss.qdss configs/c.1/f3
	ln -s functions/qdss.qdss_mdm configs/c.1/f4
	ln -s functions/cser.dun.0 configs/c.1/f5
	ln -s functions/gsi.dpl configs/c.1/f6
	ln -s functions/gsi.rmnet configs/c.1/f7
	ln -s functions/ffs.adb configs/c.1/f8
	echo 0xA0 > configs/c.1/bmAttributes
	rm -f /data/usb_bind_in_progress
	echo "binding UDC with Gadget..." $1
	echo $1 > UDC
	cd /
}

case `source /sbin/usb/target` in
	*sdxprairie* | *sdxlemur* )
		udcname=`ls -1 /sys/class/udc | head -n 1`
		run_configfs $udcname &
		;;
	* )
		echo "Composition not supported on this target "
		;;
esac
