#! /bin/sh
#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of The Linux Foundation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
#
# Short-Description: logd daemon
# Description: init.d script to start logd daemon

set -e

case "$1" in
  start)
        echo -n "Starting logd: "
        # /dev/socket
        mkdir -p /dev/socket
        echo 600 > /proc/sys/net/unix/max_dgram_qlen

        start-stop-daemon -c logd -S -b -a /sbin/logd

        #Workaround. Need to find a better solution to set the mode for sockets.
        #Already investigated starting from inittab, but even then mdev rules did not help.
        while [ ! -e /dev/socket/logd ]; do sleep 1; done
        chmod 0666 /dev/socket/logd
        while [ ! -e /dev/socket/logdr ]; do sleep 1; done
        chmod 0666 /dev/socket/logdr
        while [ ! -e /dev/socket/logdw ]; do sleep 1; done
        chmod 0222 /dev/socket/logdw

        echo "done"
        ;;
  stop)
        echo -n "Stopping logd: "
        start-stop-daemon -c logd -K -n logd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage logd { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
